version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "hongkongkiwi"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "hongkongkiwi"
    labels:
      - "dependencies"
      - "go"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "hongkongkiwi"
    labels:
      - "dependencies"
      - "docker"